fixes custom field contrib functionality
nautobot/nautobot-app-ssot pull request #350
Opened 2024-02-06 10:46 UTC by Kircheneer

Supersedes #291 
- Rename `CustomFieldAnnotation.name` to `CustomFieldAnnotation.key`
  - Keep around backwards compatibility for using `name`
- Clarify supported types of fields for identifiers
- Add tests for custom fields in identifiers

2024-02-08 16:05 UTC, jdrew82 requested changes
Just needs a slight tweak.

2024-02-15 22:56 UTC, jdrew82 approved these changes
LGTM!

2024-02-15 22:57 UTC, jdrew82 commented
@Kircheneer can we get the conflicts fixed?

2024-02-19 13:31 UTC, Kircheneer commented
Done!

2024-02-21 12:16 UTC, merged