Contrib Updates Part 1
nautobot/nautobot-app-ssot pull request #360
Opened 2024-02-20 14:55 UTC by Renrut5

First step in suggested changes for contrib files. Goal is to make a number of changes to improve usability based on my experiences with contrib but without changing current functionality.

2024-02-20 15:04 UTC, Kircheneer requested changes
I like it! Just two minor changes and a bit of CI and then we're good to go.

2024-02-20 15:04 UTC, Kircheneer commented on nautobot_ssot/contrib/utils.py
> +"""Supporting classes for SSoT contib interfacing with Nautobot."""
```suggestion
"""Supporting classes for SSoT contrib interfacing with Nautobot."""
```

2024-02-20 15:04 UTC, Kircheneer commented on nautobot_ssot/contrib/utils.py
> +
Can we rename this file to `types.py`?

2024-02-20 16:50 UTC, Renrut5 commented
@Kircheneer , got the requested changes made, once the pipeline finishes should be good to merge

2024-03-07 17:53 UTC, jdrew82 approved these changes
LGTM!

2024-03-07 17:53 UTC, merged