[WIP] Fixing issues in ACI integration
nautobot/nautobot-app-ssot pull request #486
Opened 2024-07-25 11:30 UTC by mzbroch

- Issues fixed
- MSite tag

2024-07-25 16:58 UTC, jdrew82 requested changes
Just a few things but good start.

2024-07-25 16:58 UTC, jdrew82 commented on nautobot_ssot/integrations/aci/jobs.py
> +            # self.diffsync_flags | DiffSyncFlags.SKIP_UNMATCHED_DST # pylint: disable=unsupported-binary-operation
Can we just remove this instead of commenting it out?

2024-07-25 16:58 UTC, jdrew82 commented on nautobot_ssot/integrations/aci/diffsync/adapters/aci.py
> +                        tenant=vrf_tenant or tenant_name,  # BUG fix
Can we remove the BUGFIX comments from here and the rest of your changes?

2024-07-26 12:21 UTC, pato23arg approved these changes

2024-08-14 18:44 UTC, jdrew82 commented
@mzbroch can you rebase this now that we have main sync'd with develop?

2024-08-14 20:03 UTC, jdrew82 requested changes
Just a few things to address.

2024-08-14 20:03 UTC, jdrew82 commented on nautobot_ssot/integrations/aci/diffsync/client.py
> +            # if node["topSystem"]["attributes"]["tepPool"] != "0.0.0.0":  # nosec: B104
Can we remove the commented parts if the above section is replacing it?

2024-08-14 20:03 UTC, jdrew82 commented on nautobot_ssot/integrations/aci/diffsync/client.py
> +        # TODO: rewrite using one API call -> https://10.101.40.2/api/node/class/fvBD.json?query-target=subtree&target-subtree-class=fvBD,fvRsCtx,fvSubnet
Is this potentially sensitive information we should mask?

2024-08-14 20:03 UTC, jdrew82 commented on nautobot_ssot/integrations/aci/diffsync/client.py
> +            # if node["topSystem"]["attributes"]["tepPool"] != "0.0.0.0":  # nosec: B104
Same as above.

2024-08-14 20:03 UTC, jdrew82 commented on nautobot_ssot/integrations/aci/jobs.py
> +        self.diffsync_flags = (self.diffsync_flags,)
Are we just removing the SKIP_UNMATCHED_DST DiffSync flag here? if so, we can just remove the dunder init.

2024-08-14 20:03 UTC, jdrew82 commented on nautobot_ssot/tests/aci/test_api.py
> +        self.maxDiff = None
I believe this needs to be removed. I'm surprised a linter didn't complain.

2024-08-21 18:21 UTC, jdrew82 approved these changes
Made the suggested changes as @mzbroch is on PTO.

2024-08-21 19:06 UTC, merged