Closes #520, Add instructions to enable Infoblox integration
nautobot/nautobot-app-ssot pull request #529
Opened 2024-09-03 22:07 UTC by nopg

Documentation updated

2024-09-03 23:56 UTC, jdrew82 requested changes
Just a small correction needed but looks good to me.

2024-09-03 23:56 UTC, jdrew82 commented on docs/admin/integrations/infoblox_setup.md
> +Below is an example snippet from `nautobot_config.py` that demonstrates how to enable the Itential integration:
This should be Infoblox not Itential.

2024-09-04 02:25 UTC, nopg commented on docs/admin/integrations/infoblox_setup.md
> +Below is an example snippet from `nautobot_config.py` that demonstrates how to enable the Itential integration:
Oops!

2024-09-04 15:58 UTC, jdrew82 approved these changes
LGTM!

2024-09-04 16:39 UTC, merged