Bootstrap ssot integration
nautobot/nautobot-app-ssot pull request #541
Opened 2024-09-10 12:52 UTC by bile0026

Add Bootstrap SSoT to sync in information from a local yaml file or git repository hosting information for various Nautobot "base" models.

2024-09-10 13:42 UTC, Kircheneer commented
Looks much better already

2024-09-11 02:03 UTC, jdrew82 requested changes
Just some items to address.

2024-09-11 14:06 UTC, bile0026 commented on docs/admin/integrations/bootstrap_setup.md
> +Bootstrap data can be stored in 2 fashions. Firstly, it can be stored within the `nautobot_ssot_bootstrap/fixtures` directory, or you may create a Git Repository within an existing Nautobot instance
Made some clarification here

2024-09-11 14:17 UTC, bile0026 commented on nautobot_ssot/integrations/bootstrap/diffsync/adapters/nautobot.py
> +            self.job.logger.debug(f"Loading Nautobot TenantGroup: {nb_tenant_group}, with ID: {nb_tenant_group.id}")
fixed.

2024-09-11 21:00 UTC, jdrew82 commented on docs/admin/integrations/bootstrap_setup.md
> +Bootstrap data can be stored in 2 fashions. Firstly, it can be stored within the `nautobot_ssot_bootstrap/fixtures` directory, or you may create a Git Repository within an existing Nautobot instance
I'm not seeing any clarification around the fixtures folder usage that you're suggesting. I think we still need clarification on what you're expecting users to do in that particular use case.

2024-09-11 21:03 UTC, jdrew82 reviewed
Still some stuff to address.

2024-09-11 21:03 UTC, jdrew82 commented on docs/admin/integrations/bootstrap_setup.md
> +## Process
The Process section is specifically talking about how you use the App and is not talking about installation.

2024-09-11 21:03 UTC, jdrew82 commented on nautobot_ssot/integrations/bootstrap/constants.py
> +"""Constants to be used with the nautobot_ssot_bootstrap plugin."""
OK, so delete this if it's not needed please.

2024-09-12 06:13 UTC, chadell commented on docs/user/integrations/index.md
> +- [Bootstrap](./bootstrap.md)
why twice?
```suggestion
```

2024-09-12 14:44 UTC, bile0026 commented on docs/user/integrations/index.md
> +- [Bootstrap](./bootstrap.md)
fixed

2024-09-12 14:45 UTC, bile0026 commented on docs/admin/integrations/bootstrap_setup.md
> +## Process
This is part of the configuration section?

2024-09-12 14:49 UTC, jdrew82 commented on docs/admin/integrations/bootstrap_setup.md
> +## Process
This is in the admin section which is for installation instructions. The process section that you have her is about USING the integration so should be placed in the User documentation section and should have some screenshots of using the integration.

2024-09-12 17:02 UTC, bile0026 commented on docs/admin/integrations/bootstrap_setup.md
> +Bootstrap data can be stored in 2 fashions. Firstly, it can be stored within the `nautobot_ssot_bootstrap/fixtures` directory, or you may create a Git Repository within an existing Nautobot instance
Adjusted this as well. Let me know if this makes more sense.

2024-09-19 21:26 UTC, gsnider2195 commented on docs/admin/integrations/bootstrap_setup.md
> +1. (Reccomended) Bootstrap data can be stored in a Git Repository and referenced in the app as a Git Datasource. A user should create a Git Repository in Nautobot (including any necessary Secrets and
```suggestion
1. (Recommended) Bootstrap data can be stored in a Git Repository and referenced in the app as a Git Datasource. A user should create a Git Repository in Nautobot (including any necessary Secrets and SecretsGroups for access) with the word "Bootstrap" in the name, and with a provided content type of `config contexts`. This is how the App will locate the correct repository. The data structure is flat files, and there is a naming scheme to these files. The first one required is `global_settings.yml`. This contains the main data structures of what data can be loaded `Secrets,SecretsGroups,GitRepository,DynamicGroup,Tag,etc`. You can then create additional `.yml` files with naming of your CI environments, i.e. production, development, etc for default values for specific items. This is where the environment variables described below would be matched to pull in additional data from the other YAML files defined in the directory.
```

2024-10-03 20:28 UTC, jdrew82 requested changes
One small nitpick to the docs. Also, I think you need to add yourself to the CODEOWNERS for this integration.

2024-10-03 20:28 UTC, jdrew82 commented
Also, please fix conflict with release notes for 1.5.

2024-10-03 20:36 UTC, bile0026 commented on docs/admin/integrations/bootstrap_setup.md
> +Add the Nautobot SSoT App to your poetry environment `poetry install nautobot-ssot`, then configure your `nautobot_config.py` to include the app and the settings.
Followed device42 example

2024-10-03 21:00 UTC, jdrew82 approved these changes
LGTM!

2024-10-04 16:40 UTC, merged