feat: ✨ start adding LibreNMS Integration with Locations and Devices sync
nautobot/nautobot-app-ssot pull request #636
Opened 2024-12-13 19:18 UTC by bile0026

# Closes: # N/A

## What's Changed

New SSoT Integration to sync the following information from LibreNMS:
- Location
- Device
- Interface
- IPAddress

## To Do

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2025-01-08 01:34 UTC, jdrew82 requested changes
A few things to discuss and address.

2025-01-08 01:34 UTC, jdrew82 commented on docs/user/integrations/librenms.md
> +NotYetImplemented
Can we have this be a sentence instead of just the class?

2025-01-08 01:34 UTC, jdrew82 commented on docs/user/integrations/librenms.md
> +`*` Device OS from LibreNMS is not standardized and therefore there is a mapping that can be updated in the `constants.py` file for the integration as more device manufacturers and platforms need to
Are you saying you expect a user to fork the App and update this file? Is it possible to just have this passed via the Job form instead?

2025-01-08 01:34 UTC, jdrew82 commented on nautobot_ssot/integrations/librenms/diffsync/models/base.py
> +Device.update_forward_refs()
I'm fairly certain this is from 1.x and needs to be updated.

2025-01-08 01:34 UTC, jdrew82 commented on nautobot_ssot/integrations/librenms/diffsync/models/nautobot.py
> +        adapter.job.logger.debug(f'Creating Nautobot Interface {ids["name"]}')
Should have this raise a NotImplemented or at least show a failure since it's not actually creating the Interface.

2025-01-08 01:34 UTC, jdrew82 commented on nautobot_ssot/integrations/librenms/diffsync/adapters/librenms.py
> +        print("Running tests:", is_running_tests())
Is this debug code that should be removed?

2025-01-08 01:34 UTC, jdrew82 commented on nautobot_ssot/integrations/librenms/diffsync/adapters/librenms.py
> +        if is_running_tests():
I think we need to refactor this if you're having specific code in here for when running tests.

2025-01-08 23:32 UTC, jdrew82 commented
Also, it looks like we're missing the CODEOWNERS update for this integration.

2025-01-10 02:30 UTC, bile0026 commented on docs/user/integrations/librenms.md
> +NotYetImplemented
I don't see why not. This seemed to be a standard so I followed suit. I'll update it.

2025-01-10 02:31 UTC, bile0026 commented on docs/user/integrations/librenms.md
> +`*` Device OS from LibreNMS is not standardized and therefore there is a mapping that can be updated in the `constants.py` file for the integration as more device manufacturers and platforms need to
No, I think we'd just want to add them  as we come across them. They should be the same for all instance, but there isn't a master list of every supported vendor to know what to build. This could be a candidate to make another OS-mapper in netutils though instead?

2025-01-10 02:33 UTC, bile0026 commented on nautobot_ssot/integrations/librenms/diffsync/models/base.py
> +Device.update_forward_refs()
Updated

2025-01-10 02:34 UTC, bile0026 commented on nautobot_ssot/integrations/librenms/diffsync/adapters/librenms.py
> +        print("Running tests:", is_running_tests())
Yes, good catch.

2025-01-10 02:35 UTC, bile0026 commented on nautobot_ssot/integrations/librenms/diffsync/models/nautobot.py
> +        adapter.job.logger.debug(f'Creating Nautobot Interface {ids["name"]}')
Added

2025-01-10 02:36 UTC, bile0026 commented on nautobot_ssot/integrations/librenms/diffsync/adapters/librenms.py
> +        if is_running_tests():
This is basically just to set the options you'd normally set in the job form. This seemed like the simplest place to put it, but I'm open to suggestions.

2025-01-10 16:18 UTC, jdrew82 commented on docs/user/integrations/librenms.md
> +`*` Device OS from LibreNMS is not standardized and therefore there is a mapping that can be updated in the `constants.py` file for the integration as more device manufacturers and platforms need to
I could see this being something to put in netutils later, sure.

2025-01-10 16:46 UTC, jdrew82 requested changes
Need to refactor to use mocks and patches for testing.

2025-01-10 16:46 UTC, jdrew82 commented on nautobot_ssot/integrations/librenms/diffsync/adapters/librenms.py
> +        if is_running_tests():
The proper way to do this would be to use mocks and patches in your unittests to set the Job form variables. Same with using fixtures to provide the API responses from files.

2025-01-14 15:26 UTC, jdrew82 approved these changes
LGTM!

2025-01-14 16:14 UTC, jdrew82 commented
All tests have passed locally so I'm approving this and merging it. CI issue is in core code.

2025-01-14 16:14 UTC, merged